import type { ComponentTokenContract } from '../../../build/component-tokens/types';
import { token, literal, semantic } from '../../../build/component-tokens/types';

/** Pressable action recipe. Link and icon-only treatments share this contract; icon is an independent semantic role.
 * See docs/component-semantic-rollout.md for migration decisions and design gaps.
 */
const contract: ComponentTokenContract = {
  component: 'cdr-button',
  prefix: '--cdr-button',
  interaction: 'action',
  recipe: 'pressable',
  defaults: {
    radius: token('cdr-radius-softer'),
    padding: token('cdr-space-inset-one-x-squish'),
    'font-family': token('cdr-font-family-sans'),
    'font-weight': literal(500),
    'letter-spacing': literal('-0.008rem'),
    'font-size': literal('1.6rem'),
    'line-height': literal('2.2rem'),
    'icon-size': token('cdr-icon-size'),
    'icon-padding': token('cdr-space-one-x'),
    'icon-gap': token('cdr-space-quarter-x'),
    'transition-duration': token('cdr-duration-2-x'),
    'transition-timing': token('cdr-timing-function-ease'),
    background: literal('transparent'),
    text: literal('inherit'),
    fill: literal('inherit'),
    border: literal('transparent'),
    elevation: literal('0 0 0 0 transparent'),
    'elevation-hover': token('cdr-prominence-raised'),
    'elevation-focus-visible': token('cdr-prominence-raised'),
    'elevation-active': literal('0 0 0 0 transparent'),
    'link-text': semantic('action-text-trigger', token('cdr-color-text-link-rest')),
    'link-text-hover': semantic('action-text-trigger-faint', token('cdr-color-text-link-hover')),
    'link-text-active': semantic('action-text-trigger', token('cdr-color-text-link-active')),
    'link-icon': semantic('action-icon-trigger', token('cdr-color-text-link-rest')),
    'link-icon-hover': semantic('action-icon-trigger-faint', token('cdr-color-text-link-hover')),
    'link-icon-active': semantic('action-icon-trigger', token('cdr-color-text-link-active')),
    'icon-only-fill': semantic('action-icon-neutral', token('cdr-color-icon-default')),
    'icon-only-fill-disabled': semantic(
      'action-icon-neutral-faint',
      token('cdr-color-icon-disabled'),
    ),
    'icon-only-border-focus': semantic(
      'action-border-neutral-subtle',
      token('cdr-color-border-button-secondary-active'),
    ),
  },
  variants: {
    primary: {
      identity: 'brand',
      rest: {
        surface: 'brand',
        text: 'brand',
        border: 'brand',
        icon: 'brand',
      },
      hover: {
        surface: 'brand-faint',
        text: 'brand-faint',
        border: 'brand-faint',
        icon: 'brand-faint',
      },
      'focus-visible': {
        surface: 'brand-faint',
        text: 'brand-faint',
        border: 'brand-faint',
        icon: 'brand-faint',
      },
      active: {
        surface: 'brand',
        text: 'brand',
        border: 'brand',
        icon: 'brand',
      },
      disabled: {
        surface: 'neutral-trace',
        text: 'neutral-faint',
        border: 'neutral-trace',
        icon: 'neutral-faint',
      },
      extras: {
        'active-inset': semantic(
          'action-border-brand-subtle',
          token('cdr-color-border-button-primary-active-inset'),
        ),
      },
    },
    secondary: {
      identity: 'neutral',
      rest: {
        surface: 'neutral-faint',
        text: 'neutral',
        border: 'neutral-faint',
        icon: 'neutral',
      },
      hover: {
        surface: 'neutral',
        text: 'neutral-subtle',
        border: 'neutral',
        icon: 'neutral-subtle',
      },
      'focus-visible': {
        surface: 'neutral',
        text: 'neutral-subtle',
        border: 'neutral',
        icon: 'neutral-subtle',
      },
      active: {
        surface: 'neutral-subtle',
        text: 'neutral-bold',
        border: 'neutral-subtle',
        icon: 'neutral-bold',
      },
      disabled: {
        surface: 'neutral-faint',
        text: 'neutral-faint',
        border: 'neutral-trace',
        icon: 'neutral-faint',
      },
      extras: {
        'active-inset': semantic(
          'action-border-neutral-subtle',
          token('cdr-color-border-button-secondary-active-inset'),
        ),
      },
    },
    dark: {
      identity: 'neutral',
      rest: {
        surface: 'neutral-intense',
        text: 'neutral-intense',
        border: 'neutral-intense',
        icon: 'neutral-intense',
      },
      hover: {
        surface: 'neutral-bold',
        text: 'neutral',
        border: 'neutral-intense',
        icon: 'neutral',
      },
      'focus-visible': {
        surface: 'neutral-bold',
        text: 'neutral',
        border: 'neutral-intense',
        icon: 'neutral',
      },
      active: {
        surface: 'neutral-intense',
        text: 'neutral-intense',
        border: 'neutral-intense',
        icon: 'neutral-intense',
      },
      disabled: {
        surface: 'neutral-trace',
        text: 'neutral-faint',
        border: 'neutral-trace',
        icon: 'neutral-faint',
      },
      extras: {
        'active-inset': semantic(
          'action-border-neutral-intense',
          token('cdr-color-border-button-dark-active-inset'),
        ),
      },
    },
    sale: {
      identity: 'sale',
      rest: {
        surface: 'sale',
        text: 'sale',
        border: 'sale',
        icon: 'sale',
      },
      hover: {
        surface: 'sale-faint',
        text: 'sale-faint',
        border: 'sale-faint',
        icon: 'sale-faint',
      },
      'focus-visible': {
        surface: 'sale-faint',
        text: 'sale-faint',
        border: 'sale-faint',
        icon: 'sale-faint',
      },
      active: {
        surface: 'sale',
        text: 'sale',
        border: 'sale',
        icon: 'sale',
      },
      disabled: {
        surface: 'neutral-trace',
        text: 'neutral-faint',
        border: 'neutral-trace',
        icon: 'neutral-faint',
      },
      extras: {
        'active-inset': semantic(
          'action-border-sale-subtle',
          token('cdr-color-border-button-sale-active-inset'),
        ),
      },
    },
  },
  sizes: {
    small: {
      'font-size': literal('1.4rem'),
      'line-height': literal('1.8rem'),
      padding: token('cdr-space-inset-three-quarter-x-squish'),
      'icon-padding': token('cdr-space-three-quarter-x'),
      'icon-size': literal('2rem'),
    },
    medium: {
      'font-size': literal('1.6rem'),
      'line-height': literal('2.2rem'),
      padding: token('cdr-space-inset-one-x-squish'),
      'icon-padding': token('cdr-space-one-x'),
      'icon-size': token('cdr-icon-size'),
    },
    large: {
      'font-size': literal('1.6rem'),
      'line-height': literal('2.2rem'),
      padding: token('cdr-space-inset-one-and-a-half-x-squish'),
      'icon-padding': token('cdr-space-one-and-a-half-x'),
      'icon-size': token('cdr-icon-size'),
    },
  },
  legacy: {
    'primary/background': 'cdr-color-background-button-primary-rest',
    'primary/background-hover': 'cdr-color-background-button-primary-hover',
    'primary/background-focus-visible': 'cdr-color-background-button-primary-hover',
    'primary/background-active': 'cdr-color-background-button-primary-rest',
    'primary/background-disabled': 'cdr-color-background-button-default-disabled',
    'primary/text': 'cdr-color-text-button-primary',
    'primary/text-hover': 'cdr-color-text-button-primary-hover',
    'primary/text-focus-visible': 'cdr-color-text-button-primary-hover',
    'primary/text-active': 'cdr-color-text-button-primary',
    'primary/text-disabled': 'cdr-color-text-button-primary-disabled',
    'primary/border': 'cdr-color-border-button-primary-rest',
    'primary/border-hover': 'cdr-color-border-button-primary-hover',
    'primary/border-focus-visible': 'cdr-color-border-button-primary-hover',
    'primary/border-active': 'cdr-color-border-button-primary-rest',
    'primary/border-disabled': 'cdr-color-border-button-default-disabled',
    'primary/fill': 'cdr-color-text-button-primary',
    'primary/fill-hover': 'cdr-color-text-button-primary-hover',
    'primary/fill-focus-visible': 'cdr-color-text-button-primary-hover',
    'primary/fill-active': 'cdr-color-text-button-primary',
    'primary/fill-disabled': 'cdr-color-text-button-primary-disabled',
    'secondary/background': 'cdr-color-background-button-secondary-rest',
    'secondary/background-hover': 'cdr-color-background-button-secondary-hover',
    'secondary/background-focus-visible': 'cdr-color-background-button-secondary-hover',
    'secondary/background-active': 'cdr-color-background-button-secondary-active',
    'secondary/background-disabled': 'cdr-color-background-button-secondary-disabled',
    'secondary/text': 'cdr-color-text-button-secondary',
    'secondary/text-hover': 'cdr-color-text-button-secondary-hover',
    'secondary/text-focus-visible': 'cdr-color-text-button-secondary-hover',
    'secondary/text-active': 'cdr-color-text-button-secondary-active',
    'secondary/text-disabled': 'cdr-color-text-button-secondary-disabled',
    'secondary/border': 'cdr-color-border-button-secondary-rest',
    'secondary/border-hover': 'cdr-color-border-button-secondary-hover',
    'secondary/border-focus-visible': 'cdr-color-border-button-secondary-hover',
    'secondary/border-active': 'cdr-color-border-button-secondary-active',
    'secondary/border-disabled': 'cdr-color-border-button-default-disabled',
    'secondary/fill': 'cdr-color-icon-default',
    'secondary/fill-hover': 'cdr-color-text-button-secondary-hover',
    'secondary/fill-focus-visible': 'cdr-color-text-button-secondary-hover',
    'secondary/fill-active': 'cdr-color-text-button-secondary-active',
    'secondary/fill-disabled': 'cdr-color-text-button-secondary-disabled',
    'dark/background': 'cdr-color-background-button-dark-rest',
    'dark/background-hover': 'cdr-color-background-button-dark-hover',
    'dark/background-focus-visible': 'cdr-color-background-button-dark-hover',
    'dark/background-active': 'cdr-color-background-button-dark-rest',
    'dark/background-disabled': 'cdr-color-background-button-default-disabled',
    'dark/text': 'cdr-color-text-button-dark',
    'dark/text-hover': 'cdr-color-text-button-dark-hover',
    'dark/text-focus-visible': 'cdr-color-text-button-dark-hover',
    'dark/text-active': 'cdr-color-text-button-dark-active',
    'dark/text-disabled': 'cdr-color-text-button-dark-disabled',
    'dark/border': 'cdr-color-border-button-dark-rest',
    'dark/border-hover': 'cdr-color-border-button-dark-hover',
    'dark/border-focus-visible': 'cdr-color-border-button-dark-hover',
    'dark/border-active': 'cdr-color-border-button-dark-active',
    'dark/border-disabled': 'cdr-color-border-button-default-disabled',
    'dark/fill': 'cdr-color-text-button-dark',
    'dark/fill-hover': 'cdr-color-text-button-dark-hover',
    'dark/fill-focus-visible': 'cdr-color-text-button-dark-hover',
    'dark/fill-active': 'cdr-color-text-button-dark-active',
    'dark/fill-disabled': 'cdr-color-text-button-dark-disabled',
    'sale/background': 'cdr-color-background-button-sale-rest',
    'sale/background-hover': 'cdr-color-background-button-sale-hover',
    'sale/background-focus-visible': 'cdr-color-background-button-sale-hover',
    'sale/background-active': 'cdr-color-background-button-sale-active',
    'sale/background-disabled': 'cdr-color-background-button-default-disabled',
    'sale/text': 'cdr-color-text-button-sale',
    'sale/text-hover': 'cdr-color-text-button-sale-hover',
    'sale/text-focus-visible': 'cdr-color-text-button-sale-hover',
    'sale/text-active': 'cdr-color-text-button-sale-active',
    'sale/text-disabled': 'cdr-color-text-button-sale-disabled',
    'sale/border': 'cdr-color-border-button-sale-rest',
    'sale/border-hover': 'cdr-color-border-button-sale-hover',
    'sale/border-focus-visible': 'cdr-color-border-button-sale-hover',
    'sale/border-active': 'cdr-color-border-button-sale-active',
    'sale/border-disabled': 'cdr-color-border-button-default-disabled',
    'sale/fill': 'cdr-color-text-button-sale',
    'sale/fill-hover': 'cdr-color-text-button-sale-hover',
    'sale/fill-focus-visible': 'cdr-color-text-button-sale-hover',
    'sale/fill-active': 'cdr-color-text-button-sale-active',
    'sale/fill-disabled': 'cdr-color-text-button-sale-disabled',
  },
};

export default contract;
