name: Build

on:
  push:
    branches: [next, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
      - name: Build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
          git diff --exit-code src/components/icon
