name: Unit

on:
  pull_request:
    branches:
      - next
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - run: pnpm run build --if-present
      - run: pnpm run lint
      - run: pnpm run unit
