name: Unit
on: push
jobs:
  test:
    runs-on: ubuntu-24.04

    # strategy:
    #   matrix:
    #     node-version: [20.x]
  steps:
    - name: Checkout 🛎
      uses: actions/checkout@v4

    - name: Custom tests 🧪
      uses: cypress-io/github-action@v6
      with:
        command: npm run e2e

    # Run nightwatch tests with github actions
    # https://nightwatchjs.org/guide/ci-integrations/run-nightwatch-on-github-actions.html
    # steps:
    #   - uses: actions/checkout@v4
    #   - name: Use Node.js ${{ matrix.node-version }}
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: ${{ matrix.node-version }}
    #       cache: 'npm'
    #   - run: npm ci
    #   - run: sudo apt-get install xvfb
    #   - run: npm run build --if-present
    #   - run: npm run lint
    #   - run: npm run unit
    #   - name: Run headless test
    #     run: xvfb-run --auto-servernum npm run e2e
